library(ggplot2)
library(dplyr)
library(tidyverse)
library(ggpubr)
WS1 <- read.csv(file.choose(),header=TRUE)
GC <- read.csv(file.choose(),header=TRUE)
CR <- read.csv(file.choose(),header=TRUE)
BG <- read.csv(file.choose(),header=TRUE)
WScol<- WS1[-c(21:109)]
ncol(CR)
colnames(WScol)
colnames(GC)
full_matrix <- rbind(WScol,GC,CR,BG)
bankchar<-print(select(full_matrix,1:10,17:20))
depth <-print(select(full_matrix,1:10,14))
lulc <-print(select(full_matrix,1:13))
substrate<-print(select(full_matrix,1:10,15,16))
ncol(substrate)
bankcharclean<-na.omit(bankchar)
substrateclean<-na.omit(substrate)
depthclean<-depth
lulc<-lulc %>% replace(is.na(.),0)
lulc[rowSums(is.na(lulc)) != ncol(lulc),]
